### ISSUE TITLE
[DOC] Compare file name results with a dictionary file

### ISSUE THREAD

**Issue by jmesa** [Nekmo/dirhunt#27]
--dictionary <file.txt>

To improve file detection, would be great to compare the file name results with an external dictionary.

Possible representation:
```
[200] https://domain.com/wp-content/plugins/woocommerce/includes/gateways/simplify-commerce/includes/Simplify/  (Index Of)
Interesting extension files: AccessToken.php, Authentication.php, wp-link.php, ...
Dictionary matches: wp-link.php
```
or, if --dictionary <file.txt> is selected, to show results that match with the dictionary, only.

**Comment by Nekmo** [comment]
This feature is already included since version 0.1.0 but is not being used because it is poorly documented.

http://docs.nekmo.org/dirhunt/usage.html#interesting-files
http://docs.nekmo.org/dirhunt/usage.html#comma-separated-files

It is necessary in the next version to improve the documentation.
