### ISSUE TITLE
Error with https website

### ISSUE THREAD

**Issue by xxnbyy** [Nekmo/dirhunt#37]
([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645))

**Comment by Nekmo** [comment]
This problem occurs on websites with invalid certificate. This problem will be solved this week.

Thank you.

**Comment by xxnbyy** [comment]
Cool 💯

**Comment by Nekmo** [comment]
I will use this issue to track progress. Thank you

**Comment by Nekmo** [comment]
Fixed on development branch.
