### ISSUE TITLE
Command not found issue for Windows

### ISSUE THREAD

**Issue by DaleDMT** [Nekmo/dirhunt#40]
Command not found issue after instalation according README
```
$pip install dirhunt
....
Running setup.py install for humanize ... done
Running setup.py install for dirhunt ... done
Successfully installed beautifulsoup4-4.6.0 certifi-2018.4.16 chardet-3.0.4 click-6.7 colorama-0.3.9 dirhunt-0.4.0 humanize-0.5.1 idna-2.7 requests-2.19.1 requests-mock-1.5.2 six-1.11.0 urllib3-1.23

$dirhunt http://website.com/
"dirhunt" command not found
```
Windows10 64bit, python 3.7.0

**Comment by Nekmo** [comment]
Dirhunt has not been tested on Windows. It may work with some changes but I need time to read documentation about this.

Meanwhile, you can try to install Dirhunt in Bash under Windows 10.

Sorry for the inconvenience.

**Comment by Nekmo** [comment]
Ok, commit 723c6f5cb5aa2a79fb541fe541b48200415cc763 fix this issue. Please test issue-40 branch.

Thank you!

**Comment by mrtea2211** [comment]
bbb
