### ISSUE TITLE
can't find '__main__' module in 'dirhunt'

### ISSUE THREAD

**Issue by thiruspark** [Nekmo/dirhunt#54]
Hi,

iam trying to install and run dirhunt in windows 10
installed Sphinx using $$$$ pip install Sphinx 
installed dirhunt using $$$$ python setup.py install

now when i run $$$$ dirhunt http://website.com/ iam getting error can't find '__main__' module in 'dirhunt'

please suggest me how to fix it

**Comment by Nekmo** [comment]
Hello,

Can you please try to install Dirhunt using `pip install dirhunt`?

This is the official installation method. Thanks.

**Comment by Nekmo** [comment]
Closed due to inactivity.
