### ISSUE TITLE
problem(windows10 python3)

### ISSUE THREAD

**Issue by maybe-why-not** [Nekmo/dirhunt#68]
`>>> import dirhunt`
`>>> dirhunt`
`<module 'dirhunt' from 'F:\\Python36\\lib\\site-packages\\dirhunt\\__init__.py'>`
`>>> dirhunt http://www.sgjgdj.org.cn`
`  File "<stdin>", line 1`
`    dirhunt http://www.sgjgdj.org.cn`
`                     ^`
`SyntaxError: invalid syntax`
`>>> dirhunt --help`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`TypeError: bad operand type for unary -: '_Helper'`
`>>>`

**Comment by Nekmo** [comment]
You have to use dirhunt from a console. Not from a Python interpreter.

**Comment by Nekmo** [comment]
Closed due to inactivity.
