### ISSUE TITLE
Feature request: Check java script files for dirhunt

### ISSUE THREAD

**Issue by cetriext** [Nekmo/dirhunt#69]
First of all thanks for dirhunt.
I'm requesting a feature if its possible hunt directories in javascript files.
simillar tool https://github.com/GerbenJavado/LinkFinder extract links from .js files

**Comment by Nekmo** [comment]
I think it's a good idea :) Thanks for the contribution!

**Comment by Nekmo** [comment]
Added to milestone v0.8.0!

**Comment by Nekmo** [comment]
Available in v0.8.0 development version!
