### ISSUE TITLE
Meta refresh tag not considered

### ISSUE THREAD

**Issue by simon-wessel** [Nekmo/dirhunt#71]
dirhunt does not consider meta refreshes that redirect to another web page:

`<meta http-equiv="refresh" content="0;URL=/someotherdirectory">`

This might also be true for JavaScript redirects, but I haven't tested that yet.

**Comment by Nekmo** [comment]
Added to milestone v0.8.0!

**Comment by Nekmo** [comment]
Now available in the development branch! :)

**Comment by simon-wessel** [comment]
That's great, thanks :+1:
