### ISSUE TITLE
Missing dependencies for SOCKS support.

### ISSUE THREAD

**Issue by maxxer** [Nekmo/dirhunt#72]
After installing via pip3 and even after installing deps from `py3-requirements.txt` I got the following:

```
dirhunt https://www.aaa.net/ --proxies tor
Welcome to Dirhunt v0.6.0 using Python 3.7.4
[ERROR] https://www.aaa.net/ (Missing dependencies for SOCKS support.)
[ERROR] https://www.aaa.net/forums/posts/1471313/ (Missing dependencies for SOCKS support.)
[ERROR] https://www.aaa.net/forums/posts/6369600/ (Missing dependencies for SOCKS support.)
```

I fixed by running  `pip3 install 'urllib3[socks]'` (on macOS). Maybe worth mentioning at least in the docs?

**Comment by Nekmo** [comment]
Yes, it is not in the documentation. I will add it, thanks :+1:
