### ISSUE TITLE
Dirhunt takes a URL but proceeds to scan its host

### ISSUE THREAD

**Issue by Vbbab** [Nekmo/dirhunt#86]
Not sure if this is intended behavior, but according to DirHunt's help, it takes a list of URLs and dirhunts *below that URL* (?)

However, right now in `v0.6.0` DirHunt takes a URL and proceeds to scan the *host* of the URL (i.e., takes `https://www.google.com/tools` and proceeds to dirhunt `https://www.google.com`.

Screenshot:
![image](https://user-images.githubusercontent.com/44555590/100313308-3740d780-2f69-11eb-9e39-ac579ed2744a.png)

Is this intended behavior? If not, what could be causing this bug?

**Comment by Nekmo** [comment]
It is the intended behavior, Dirhunt tries to find all possible urls on the website. You can put one or more complete urls to help Dirhunt with the analysis.

For example for the url https://website.com/admin/site/ it will find in the following paths:

- https://website.com/admin/site/
- https://website.com/admin/
- https://website.com/

**Comment by Vbbab** [comment]
OK thanks for the info! Closing this as it is no longer an issue.

**Comment by Nekmo** [comment]
You are welcome!

**Comment by its0x08** [comment]
Hello,
To me this is still an issue!!
I need to scan only a **/subdir/** of the host and it starts from **/**
In **/** there is nothing in my case, and in **/upload/** a ton of _subdirs_ with huge _depth_ that I dont want to inspect one by one or using **wget** .
Can you add a flag **--base-dir** or something so we can specify a base other than **/** !!!!
Thank you!
